CREATE TABLE IF NOT EXISTS landing_page_integrations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL,
  type ENUM('landing_page') NOT NULL DEFAULT 'landing_page',
  status ENUM('Draft','Active','Disabled') NOT NULL DEFAULT 'Draft',
  isEnabled TINYINT NOT NULL DEFAULT 0,
  allowedDomains JSON NULL,
  endpointPath VARCHAR(255) NOT NULL,
  sourceName VARCHAR(255) NULL,
  defaultPageTitle VARCHAR(255) NULL,
  defaultStage VARCHAR(100) NOT NULL DEFAULT 'New',
  assignmentRule ENUM('round_robin','fixed_owner','by_campaign') NOT NULL DEFAULT 'round_robin',
  fixedOwnerId INT NULL,
  dedupRule ENUM('phone','external_id','phone_and_source') NOT NULL DEFAULT 'phone',
  attributionMode ENUM('first_touch','last_touch','both') NOT NULL DEFAULT 'both',
  fieldMapping JSON NULL,
  securityConfig JSON NULL,
  notificationConfig JSON NULL,
  tags JSON NULL,
  scoringRules JSON NULL,
  successMessage TEXT NULL,
  redirectUrl TEXT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deletedAt TIMESTAMP NULL,
  UNIQUE KEY uq_landing_page_integrations_slug (slug),
  KEY idx_landing_page_integrations_status (status),
  KEY idx_landing_page_integrations_deletedAt (deletedAt)
);

CREATE TABLE IF NOT EXISTS landing_page_submission_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  integrationId INT NOT NULL,
  status ENUM('received','validated','blocked','pushed_to_crm','duplicate','failed') NOT NULL DEFAULT 'received',
  ipAddress VARCHAR(128) NULL,
  userAgent TEXT NULL,
  origin TEXT NULL,
  payloadJson JSON NULL,
  trackingJson JSON NULL,
  errorMessage TEXT NULL,
  leadId INT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  processedAt TIMESTAMP NULL,
  KEY idx_lp_submission_logs_integrationId (integrationId),
  KEY idx_lp_submission_logs_status (status),
  KEY idx_lp_submission_logs_leadId (leadId),
  CONSTRAINT fk_lp_submission_logs_integration FOREIGN KEY (integrationId) REFERENCES landing_page_integrations(id)
);
