CREATE TABLE IF NOT EXISTS `lead_meeting_briefs` (
  `id` int NOT NULL AUTO_INCREMENT,
  `leadId` int NOT NULL,
  `tamUserId` int NOT NULL,
  `salesUserId` int DEFAULT NULL,
  `meetingAt` timestamp NOT NULL,
  `source` enum('activity','calendar','manual') NOT NULL DEFAULT 'manual',
  `calendarEventId` varchar(255) DEFAULT NULL,
  `status` enum('Draft','ReadyForMeeting','Completed') NOT NULL DEFAULT 'Draft',
  `talkingPoints` text,
  `objectives` text,
  `clientNeedsToHear` text,
  `redFlags` text,
  `prepareReminderId` int DEFAULT NULL,
  `salesReminderId` int DEFAULT NULL,
  `readyAt` timestamp NULL DEFAULT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_meetingbrief_leadId` (`leadId`),
  KEY `idx_meetingbrief_tamUserId` (`tamUserId`),
  KEY `idx_meetingbrief_salesUserId` (`salesUserId`),
  KEY `idx_meetingbrief_status` (`status`),
  KEY `idx_meetingbrief_meetingAt` (`meetingAt`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
