import { z } from "zod";

export const landingPageNotificationConfigSchema = z.object({
  email: z.object({
    enabled: z.boolean().default(true),
    recipients: z.array(z.string().email()).default([]),
    notifyOn: z.array(z.enum(["lead_created", "duplicate", "integration_error", "blocked"])).default(["lead_created"]),
  }).default({ enabled: true, recipients: [], notifyOn: ["lead_created"] }),
  slack: z.object({
    enabled: z.boolean().default(false),
    webhookUrl: z.string().url().optional().or(z.literal("")),
    channel: z.string().optional(),
    mention: z.string().optional(),
    notifyOn: z.array(z.enum(["lead_created", "duplicate", "integration_error", "blocked"])).default(["lead_created"]),
  }).default({ enabled: false, webhookUrl: "", channel: "", mention: "", notifyOn: ["lead_created"] }),
});

export const landingPageSecurityConfigSchema = z.object({
  allowedOrigins: z.array(z.string()).default([]),
  requireTurnstile: z.boolean().default(false),
  turnstileSecret: z.string().optional(),
  honeypotField: z.string().default("website"),
  minSubmitSeconds: z.number().int().min(0).default(3),
  rateLimitWindowMinutes: z.number().int().min(1).default(10),
  rateLimitMaxRequests: z.number().int().min(1).default(5),
});

export const landingPageFieldMappingSchema = z.object({
  name: z.string().default("name"),
  phone: z.string().default("phone"),
  businessProfile: z.string().default("businessLink"),
  campaignName: z.string().default("utm_campaign"),
  sourceMetadata: z.record(z.string(), z.string()).default({
    pageSlug: "pageSlug",
    pageTitle: "pageTitle",
    landingUrl: "landingUrl",
    referrer: "referrer",
    utm_source: "utm_source",
    utm_medium: "utm_medium",
    utm_campaign: "utm_campaign",
    utm_content: "utm_content",
    utm_term: "utm_term",
    gclid: "gclid",
    fbclid: "fbclid",
    ttclid: "ttclid",
    msclkid: "msclkid",
    first_touch_source: "first_touch_source",
    first_touch_medium: "first_touch_medium",
    first_touch_campaign: "first_touch_campaign",
    last_touch_source: "last_touch_source",
    last_touch_medium: "last_touch_medium",
    last_touch_campaign: "last_touch_campaign",
    session_id: "session_id",
    visitor_id: "visitor_id",
    submitted_at: "submitted_at",
  }),
  customFields: z.record(z.string(), z.string()).default({
    businessType: "businessType",
    acquisitionChannels: "acquisitionChannels",
    budget: "budget",
    challenge: "challenge",
    decisionMaker: "decisionMaker",
    preferredContactTime: "preferredContactTime",
    businessLink: "businessLink",
  }),
});

export const landingPageIntegrationInputSchema = z.object({
  name: z.string().min(2),
  slug: z.string().min(2).regex(/^[a-z0-9-]+$/),
  status: z.enum(["Draft", "Active", "Disabled"]).default("Draft"),
  isEnabled: z.boolean().default(true),
  allowedDomains: z.array(z.string()).default([]),
  endpointPath: z.string().min(3),
  sourceName: z.string().optional(),
  defaultPageTitle: z.string().optional(),
  defaultStage: z.string().default("New"),
  assignmentRule: z.enum(["round_robin", "fixed_owner", "by_campaign"]).default("round_robin"),
  fixedOwnerId: z.number().nullable().optional(),
  dedupRule: z.enum(["phone", "external_id", "phone_and_source"]).default("phone"),
  attributionMode: z.enum(["first_touch", "last_touch", "both"]).default("both"),
  fieldMapping: landingPageFieldMappingSchema.default({}),
  securityConfig: landingPageSecurityConfigSchema.default({}),
  notificationConfig: landingPageNotificationConfigSchema.default({}),
  tags: z.array(z.string()).default([]),
  scoringRules: z.array(z.object({
    field: z.string(),
    operator: z.enum(["equals", "includes"]),
    value: z.string(),
    score: z.number().int(),
  })).default([]),
  successMessage: z.string().optional(),
  redirectUrl: z.string().url().optional().or(z.literal("")),
});

export const publicLeadPayloadSchema = z.object({
  name: z.string().optional(),
  phone: z.string().min(5),
  businessType: z.string().optional(),
  acquisitionChannels: z.array(z.string()).optional(),
  budget: z.string().optional(),
  challenge: z.string().optional(),
  decisionMaker: z.string().optional(),
  preferredContactTime: z.string().optional(),
  businessLink: z.string().optional(),
  pageSlug: z.string().optional(),
  pageTitle: z.string().optional(),
  formName: z.string().optional(),
  landingUrl: z.string().optional(),
  referrer: z.string().optional(),
  utm_source: z.string().optional(),
  utm_medium: z.string().optional(),
  utm_campaign: z.string().optional(),
  utm_content: z.string().optional(),
  utm_term: z.string().optional(),
  gclid: z.string().optional(),
  fbclid: z.string().optional(),
  ttclid: z.string().optional(),
  msclkid: z.string().optional(),
  first_touch_source: z.string().optional(),
  first_touch_medium: z.string().optional(),
  first_touch_campaign: z.string().optional(),
  last_touch_source: z.string().optional(),
  last_touch_medium: z.string().optional(),
  last_touch_campaign: z.string().optional(),
  session_id: z.string().optional(),
  visitor_id: z.string().optional(),
  submitted_at: z.string().optional(),
  turnstileToken: z.string().optional(),
  website: z.string().optional(),
  externalSubmissionId: z.string().optional(),
}).passthrough();

export type LandingPageIntegrationInput = z.infer<typeof landingPageIntegrationInputSchema>;
export type PublicLeadPayload = z.infer<typeof publicLeadPayloadSchema>;
